### ISSUE TITLE
ubuntu2204 の idempotence で失敗する

### ISSUE THREAD

**Issue by ktooi** [ktooi/ansible-role-slapd#7]
ubuntu2204 の indempotence テストで下記のタスクに失敗する。
```
  TASK [ktooi.slapd : Start up the provider and a consumer/s on the backend (2/2)] ***
  fatal: [instance]: FAILED! => {"changed": false, "details": "{'desc': 'Type or value exists', 'info': 'modify/add: olcMultiProvider: value #0 already exists'}", "msg": "Attribute action failed."}
```
該当のタスクの内容は下記で、特に問題はないように見受けられる。
```yaml
- name: Start up the provider and a consumer/s on the backend (2/2)
  become: true
  ldap_attrs:
    dn: '{{ slapd_olcDatabase_type_dn }}'
    attributes:
      olcMirrorMode: 'TRUE'
    state: exact
  tags:
    - slapd_replication
```
